name: "pre-release"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Add dependencies
        run: |
          yarn

      - name: Build
        run: |
          yarn run release

      - name: "Publish the build"
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.CODE_BOT_DEPLOY_CODE }}
          automatic_release_tag: latest
          prerelease: true
          title: Development Build
          files: |
            webfiles.zip