name: "Release web bundle"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Add dependencies
        run: |
          yarn

      - name: Build
        run: |
          yarn run release

      - name: Publish The Build
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: Development Build
          files: |
            webfiles.zip
      
      - name: Trigger Container Build
        run: |
          curl -XPOST -u "${{ secrets.BOT_NAME }}:${{ secrets.BOT_ACCESS_CODE }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/salesian-college/edge-server/dispatches --data '{"event_type": "build_container"}'